spring:
  application:
    name: gateway-service
  server:
    port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

  #Route mapping
  zuul:
    routes:
      employee-service:
        path: /employee/**
        serviceId: EMPLOYEE-SERVICE