server:
  port: 9082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

  ##App Properties
app:
  jwtSecret: somesecretkey
  jwtExpirationInMs: 604800000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/